title: Khatcher O. Margossian
logo: "assets/imgs/header_img.jpg?raw=true"
description: >
  <br>
  M.D./Ph.D. student at Rush University Medical Center. <br>
  <p class="codepen" data-height="300" data-default-tab="html,result" data-slug-hash="YPYgNj" data-user="cdunnnnnnn" style="height: 300px; box-sizing: border-box; display: flex; align-items: center; justify-content: center; border: 2px solid; margin: 1em 0; padding: 1em;">
  <span>See the Pen <a href="https://codepen.io/cdunnnnnnn/pen/YPYgNj">
  CSS Chicago flag</a> by Christopher Dunn (<a href="https://codepen.io/cdunnnnnnn">@cdunnnnnnn</a>)
  on <a href="https://codepen.io">CodePen</a>.</span>
  </p>
  <script async src="https://cpwebassets.codepen.io/assets/embed/ei.js"></script>
  <br><br>
  <a href="https://www.linkedin.com/in/khatcher-margossian-2b01aa44/">View My LinkedIn Profile</a>

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
